---
- name: yum update
  yum:
    name: '*'
    state: latest
  register: yum_update
  tags:
    - yum-update

- name: reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  when: yum_update.changed

- name: wait for reboot
  wait_for_connection:
    delay: 15
    sleep: 5
    timeout: 300
  when: yum_update.changed
