---
- name: kubeadm alpha phase certs all
  command: kubeadm alpha phase certs all --config /tmp/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/pki/apiserver-etcd-client.crt
  tags:
    - control-plane
    - kubeadm-alpha-phase-command

- name: kubeadm alpha phase kubelet config write-to-disk
  command: kubeadm alpha phase kubelet config write-to-disk --config /tmp/kubeadm-config.yaml
  tags:
    - control-plane
    - kubeadm-alpha-phase-command

- name: kubeadm alpha phase kubelet write-env-file
  command: kubeadm alpha phase kubelet write-env-file --config /tmp/kubeadm-config.yaml
  args:
    creates: /var/lib/kubelet/kubeadm-flags.env
  tags:
    - control-plane
    - kubeadm-alpha-phase-command

- name: kubeadm alpha phase kubeconfig kubelet
  command: kubeadm alpha phase kubeconfig kubelet --config /tmp/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/kubelet.conf
  tags:
    - control-plane
    - kubeadm-alpha-phase-command

- name: start kubelet
  service:
    name: kubelet
    state: started
  tags:
    - control-plane
    - kubeadm-alpha-phase-command
