---
- name: install libselinux-python
  yum:
    name: libselinux-python
  tags:
    - selinux

- name: set selinux permissive
  selinux:
    policy: targeted
    state: permissive
  tags:
    - selinux

- name: setenforce 0
  command: /usr/sbin/setenforce 0
  tags:
    - selinux
