---
- name: kubectl apply calico etcd.yaml
  command: kubectl apply -f https://docs.projectcalico.org/{{ calico_version }}/getting-started/kubernetes/installation/hosted/etcd.yaml
  tags:
    - control-plane
    - calico

- name: kubectl apply calico.yaml
  command: kubectl apply -f https://docs.projectcalico.org/{{ calico_version }}/getting-started/kubernetes/installation/hosted/calico.yaml
  tags:
    - control-plane
    - calico
