---
#- name: install kubelet
#  yum:
#    name: "{{ item }}"
#    disable_excludes: kubernetes
#  with_items:
#    - kubelet
#    - kubeadm
#    - kubectl
#  tags:
#    - kube-tools

- name: install kubelet
  command: yum install -y kubelet-{{ kube_version_yum }} kubeadm-{{ kube_version_yum }} kubectl-{{ kube_version_yum }} --disableexcludes=kubernetes
  args:
    warn: no
  tags:
    - kube-tools
